### ISSUE TITLE
Is het correct om adressering.indicatieVastgesteldVerblijftNietOpAdres in de OAS bij de types Adres en Locatie op te nemen?

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-historie-bevragen#107]
Voorstel: adressering.indicatieVastgesteldVerblijftNietOpAdres te verwijderen, omdat deze ook al onderdeel is van Adres en Locatie.

**Comment by MelvLee** [comment]
fixed in commit: https://github.com/BRP-API/Haal-Centraal-BRP-historie-bevragen/commit/b04b3461e396108ed864daf53c5199e22adfed74
