### ISSUE TITLE
opschonen features en docs in Haal-Centraal-BRP-historie-bevragen repo

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-historie-bevragen#117]
Er staan nog features van nationaliteithistorie, partnerhistorie enz.
Er staan nog features die verplaatst (feitelijk gekopieerd) zijn naar historie-data-service repo
In docs staat nog een aantal oude documenten die ernstig achterhaald zijn.

**Comment by MelvLee** [comment]
feature map + bijbehorende scripts verwijderd
src map + aan code gerelateerde bestanden verwijderd

**Comment by CathyDingemanse** [comment]
done
