### ISSUE TITLE
Hoe gaan we om met de base-url bij implementatie door RvIG

### ISSUE THREAD

**Issue by JohanBoer** [BRP-API/Haal-Centraal-BRP-historie-bevragen#29]
Voor v1.0.0 is historie in een aparte API ondergebracht (anders dan in v0.9.0). Hiermee is de discussie op gang gekomen of het dan noodzakelijk is om de base-url aan te passen en is de vraag boven gekomen of de base-url aangepast gaat worden als de RvIG de Haal-Centraal API's gaat leveren. 

Deze onderwerp moet op de agenda komen als het RvIG deze API's gaat leveren.

**Comment by fsamwel** [comment]
ik denk in bredere zin dat het goed is duidelijk te zijn over of de href in links relatief (interne links), volledig, of templated (met base url templated) moet zijn.

- De BAG API levert altijd volledige urls.
- De BRK API levert voor interne links relatieve urls ("href": "/kadasternatuurlijkpersonen/70882239"), voor externe links volledige links.
